export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";
export const SET_CURRENT_PRODUCER = "SET_CURRENT_PRODUCER";

export const SET_CART = "SET_CART";
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const UPDATE_TOTAL_PRICE_ON_DELETE = "UPDATE_TOTAL_PRICE_ON_DELETE";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
