export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";
export const SET_CURRENT_PRODUCER = "SET_CURRENT_PRODUCER";

export const SET_CART = "SET_CART";
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const UPDATE_TOTAL_PRICE_ON_DELETE = "UPDATE_TOTAL_PRICE_ON_DELETE";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const PURCHASE_ORDER_INIT = "PURCHASE_ORDER_INIT";
export const PURCHASE_ORDER_START = "PURCHASE_ORDER_START";
export const PURCHASE_ORDER_FAIL = "PURCHASE_ORDER_FAIL";
export const PURCHASE_ORDER_SUCCESS = "PURCHASE_ORDER_SUCCESS";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
